 #!/usr/bin/env python3                                                                                                              
  # convert_moon.py  —  usage: python3 convert_moon.py moon.jpg
  import sys                                                                                                                          
  from PIL import Image
  import numpy as np                                                                                                                  
                                                                                                                                      
  src = sys.argv[1] if len(sys.argv) > 1 else "moon.jpg"
  img = Image.open(src).convert("RGB").resize((240, 240), Image.LANCZOS)                                                              
                                                                                                                                      
  px  = np.array(img, dtype=np.uint16)                                                                                                
  r   = (px[:,:,0] >> 3)                                                                                                              
  g   = (px[:,:,1] >> 2)                                                                                                              
  b   = (px[:,:,2] >> 3)                                    
  rgb = ((r << 11) | (g << 5) | b).flatten()
                                                                                                                                      
  with open("moon_image.h", "w") as f:
      f.write("#pragma once\n")                                                                                                       
      f.write("#include <pgmspace.h>\n\n")                                                                                            
      f.write("// 240×240 RGB565 full-moon image — generated by convert_moon.py\n")
      f.write("static const uint16_t MOON_IMAGE[] PROGMEM = {\n")                                                                     
      for i, v in enumerate(rgb):                                                                                                     
          f.write(f"0x{v:04X},")                                                                                                      
          if (i + 1) % 16 == 0:                                                                                                       
              f.write("\n")                                                                                                           
      f.write("\n};\n")
                                                                                                                                      
  print(f"Written moon_image.h  ({len(rgb)*2//1024} KB)")      
